//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.wcsModel.version100.wcsCapabilities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "axisDescription"
})
@XmlRootElement(name = "axisDescription", namespace = "http://www.opengis.net/wcs")
public class AxisDescription {

    @XmlElement(name = "AxisDescription", namespace = "http://www.opengis.net/wcs", type = AxisDescriptionType.class)
    protected AxisDescriptionType axisDescription;

    /**
     * Gets the value of the axisDescription property.
     * 
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcsModel.version100.wcsCapabilities.AxisDescriptionType}
     */
    public AxisDescriptionType getAxisDescription() {
        return axisDescription;
    }

    /**
     * Sets the value of the axisDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcsModel.version100.wcsCapabilities.AxisDescriptionType}
     */
    public void setAxisDescription(AxisDescriptionType value) {
        this.axisDescription = value;
    }

}
