//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.wcsModel.version100.wcsCapabilities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.n52.oxf.serviceAdapters.wcs.model.version100.gml.CodeListType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "SupportedFormatsType", namespace = "http://www.opengis.net/wcs")
public class SupportedFormatsType {

    @XmlElement(name = "formats", namespace = "http://www.opengis.net/wcs", type = CodeListType.class)
    protected List<CodeListType> formats;
    @XmlAttribute(name = "nativeFormat", namespace = "")
    protected String nativeFormat;

    protected List<CodeListType> _getFormats() {
        if (formats == null) {
            formats = new ArrayList<CodeListType>();
        }
        return formats;
    }

    /**
     * Gets the value of the formats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.n52.oxf.serviceAdapters.wcs.model.version100.gml.CodeListType}
     * 
     */
    public List<CodeListType> getFormats() {
        return this._getFormats();
    }

    /**
     * Gets the value of the nativeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getNativeFormat() {
        return nativeFormat;
    }

    /**
     * Sets the value of the nativeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setNativeFormat(String value) {
        this.nativeFormat = value;
    }

}
