/**
 * ﻿Copyright (C) 2012-2015 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the Free
 * Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of the
 * following licenses, the combination of the program with the linked library is
 * not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed under
 * the aforementioned licenses, is permitted by the copyright holders if the
 * distribution is compliant with both the GNU General Public License version 2
 * and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.wcs.capabilities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.n52.oxf.wcs.capabilities.AxisDescriptionType.Values;
import org.n52.oxf.wcs.capabilities.DCPTypeType.HTTP;
import org.n52.oxf.wcs.capabilities.DCPTypeType.HTTP.Get;
import org.n52.oxf.wcs.capabilities.DCPTypeType.HTTP.Post;
import org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception;
import org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request;
import org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities;
import org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage;
import org.n52.oxf.wcs.model.CodeListType;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.n52.oxf.wcsModel.version100.wcsCapabilities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponsiblePartyTypePositionName_QNAME = new QName("http://www.opengis.net/wcs", "positionName");
    private final static QName _ResponsiblePartyTypeOrganisationName_QNAME = new QName("http://www.opengis.net/wcs", "organisationName");
    private final static QName _ResponsiblePartyTypeContactInfo_QNAME = new QName("http://www.opengis.net/wcs", "contactInfo");
    private final static QName _ResponsiblePartyTypeIndividualName_QNAME = new QName("http://www.opengis.net/wcs", "individualName");
    private final static QName _AxisDescription_QNAME = new QName("http://www.opengis.net/wcs", "AxisDescription");
    private final static QName _CoverageOffering_QNAME = new QName("http://www.opengis.net/wcs", "CoverageOffering");
    private final static QName _MetadataLink_QNAME = new QName("http://www.opengis.net/wcs", "metadataLink");
    private final static QName _Description_QNAME = new QName("http://www.opengis.net/wcs", "description");
    private final static QName _TimeSequence_QNAME = new QName("http://www.opengis.net/wcs", "TimeSequence");
    private final static QName _TimePeriod_QNAME = new QName("http://www.opengis.net/wcs", "timePeriod");
    private final static QName _TemporalDomain_QNAME = new QName("http://www.opengis.net/wcs", "temporalDomain");
    private final static QName _DomainSet_QNAME = new QName("http://www.opengis.net/wcs", "domainSet");
    private final static QName _SingleValue_QNAME = new QName("http://www.opengis.net/wcs", "singleValue");
    private final static QName _WCSCapabilities_QNAME = new QName("http://www.opengis.net/wcs", "WCS_Capabilities");
    private final static QName _LonLatEnvelope_QNAME = new QName("http://www.opengis.net/wcs", "lonLatEnvelope");
    private final static QName _CoverageOfferingBrief_QNAME = new QName("http://www.opengis.net/wcs", "CoverageOfferingBrief");
    private final static QName _InterpolationMethod_QNAME = new QName("http://www.opengis.net/wcs", "interpolationMethod");
    private final static QName _SupportedCRSs_QNAME = new QName("http://www.opengis.net/wcs", "supportedCRSs");
    private final static QName _SpatialDomain_QNAME = new QName("http://www.opengis.net/wcs", "spatialDomain");
    private final static QName _Name_QNAME = new QName("http://www.opengis.net/wcs", "name");
    private final static QName _SupportedInterpolations_QNAME = new QName("http://www.opengis.net/wcs", "supportedInterpolations");
    private final static QName _Formats_QNAME = new QName("http://www.opengis.net/wcs", "formats");
    private final static QName _Interval_QNAME = new QName("http://www.opengis.net/wcs", "interval");
    private final static QName _RangeSet_QNAME = new QName("http://www.opengis.net/wcs", "RangeSet");
    private final static QName _Service_QNAME = new QName("http://www.opengis.net/wcs", "Service");
    private final static QName _SupportedFormats_QNAME = new QName("http://www.opengis.net/wcs", "supportedFormats");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.n52.oxf.wcsModel.version100.wcsCapabilities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception}
     * 
     */
    public Exception createWCSCapabilityTypeException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities}
     * 
     */
    public VendorSpecificCapabilities createWCSCapabilityTypeVendorSpecificCapabilities() {
        return new VendorSpecificCapabilities();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ContactType}
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.SupportedFormatsType}
     * 
     */
    public SupportedFormatsType createSupportedFormatsType() {
        return new SupportedFormatsType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ResponsiblePartyType}
     * 
     */
    public ResponsiblePartyType createResponsiblePartyType() {
        return new ResponsiblePartyType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage}
     * 
     */
    public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage createWCSCapabilityTypeRequestDescribeCoverage() {
        return new org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.CoverageOfferingType}
     * 
     */
    public CoverageOfferingType createCoverageOfferingType() {
        return new CoverageOfferingType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage}
     * 
     */
    public GetCoverage createWCSCapabilityTypeRequestGetCoverage() {
        return new GetCoverage();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.DCPTypeType.HTTP}
     * 
     */
    public HTTP createDCPTypeTypeHTTP() {
        return new HTTP();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.DCPTypeType.HTTP.Get}
     * 
     */
    public Get createDCPTypeTypeHTTPGet() {
        return new Get();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.Keywords}
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.LonLatEnvelopeBaseType}
     * 
     */
    public LonLatEnvelopeBaseType createLonLatEnvelopeBaseType() {
        return new LonLatEnvelopeBaseType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.MetadataLinkType}
     * 
     */
    public MetadataLinkType createMetadataLinkType() {
        return new MetadataLinkType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ServiceType}
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilitiesType}
     * 
     */
    public WCSCapabilitiesType createWCSCapabilitiesType() {
        return new WCSCapabilitiesType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.SupportedInterpolationsType}
     * 
     */
    public SupportedInterpolationsType createSupportedInterpolationsType() {
        return new SupportedInterpolationsType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.CoverageOfferingBriefType}
     * 
     */
    public CoverageOfferingBriefType createCoverageOfferingBriefType() {
        return new CoverageOfferingBriefType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.RangeSetType}
     * 
     */
    public RangeSetType createRangeSetType() {
        return new RangeSetType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.Interval}
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.DescribeCoverage}
     * 
     */
    public org.n52.oxf.wcs.capabilities.DescribeCoverage createDescribeCoverage() {
        return new org.n52.oxf.wcs.capabilities.DescribeCoverage();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request}
     * 
     */
    public Request createWCSCapabilityTypeRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.DCPTypeType}
     * 
     */
    public DCPTypeType createDCPTypeType() {
        return new DCPTypeType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.RangeSet}
     * 
     */
    public RangeSet createRangeSet() {
        return new RangeSet();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.SupportedCRSsType}
     * 
     */
    public SupportedCRSsType createSupportedCRSsType() {
        return new SupportedCRSsType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.DomainSetType}
     * 
     */
    public DomainSetType createDomainSetType() {
        return new DomainSetType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.LonLatEnvelopeType}
     * 
     */
    public LonLatEnvelopeType createLonLatEnvelopeType() {
        return new LonLatEnvelopeType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.CoverageDescription}
     * 
     */
    public CoverageDescription createCoverageDescription() {
        return new CoverageDescription();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ValueEnumType}
     * 
     */
    public ValueEnumType createValueEnumType() {
        return new ValueEnumType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.DCPTypeType.HTTP.Post}
     * 
     */
    public Post createDCPTypeTypeHTTPPost() {
        return new Post();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.IntervalType}
     * 
     */
    public IntervalType createIntervalType() {
        return new IntervalType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.AxisDescription}
     * 
     */
    public AxisDescription createAxisDescription() {
        return new AxisDescription();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ValueEnumBaseType}
     * 
     */
    public ValueEnumBaseType createValueEnumBaseType() {
        return new ValueEnumBaseType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.GetCapabilities}
     * 
     */
    public org.n52.oxf.wcs.capabilities.GetCapabilities createGetCapabilities() {
        return new org.n52.oxf.wcs.capabilities.GetCapabilities();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.SpatialDomainType}
     * 
     */
    public SpatialDomainType createSpatialDomainType() {
        return new SpatialDomainType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.AxisDescriptionType}
     * 
     */
    public AxisDescriptionType createAxisDescriptionType() {
        return new AxisDescriptionType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities}
     * 
     */
    public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities createWCSCapabilityTypeRequestGetCapabilities() {
        return new org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.AxisDescriptionType.Values}
     * 
     */
    public Values createAxisDescriptionTypeValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.TimePeriodType}
     * 
     */
    public TimePeriodType createTimePeriodType() {
        return new TimePeriodType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.TimeSequenceType}
     * 
     */
    public TimeSequenceType createTimeSequenceType() {
        return new TimeSequenceType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ValueRangeType}
     * 
     */
    public ValueRangeType createValueRangeType() {
        return new ValueRangeType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType}
     * 
     */
    public WCSCapabilityType createWCSCapabilityType() {
        return new WCSCapabilityType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.TelephoneType}
     * 
     */
    public TelephoneType createTelephoneType() {
        return new TelephoneType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.TypedLiteralType}
     * 
     */
    public TypedLiteralType createTypedLiteralType() {
        return new TypedLiteralType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.AddressType}
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.ContentMetadata}
     * 
     */
    public ContentMetadata createContentMetadata() {
        return new ContentMetadata();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.MetadataAssociationType}
     * 
     */
    public MetadataAssociationType createMetadataAssociationType() {
        return new MetadataAssociationType();
    }

    /**
     * Create an instance of {@link org.n52.oxf.wcs.capabilities.OnlineResourceType}
     * 
     */
    public OnlineResourceType createOnlineResourceType() {
        return new OnlineResourceType();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<java.lang.String>}
     * 
     */
    @XmlElementDecl(name = "positionName", namespace = "http://www.opengis.net/wcs", scope = ResponsiblePartyType.class)
    public JAXBElement<String> createResponsiblePartyTypePositionName(String value) {
        return new JAXBElement<String>(_ResponsiblePartyTypePositionName_QNAME, ((Class) String.class), ResponsiblePartyType.class, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<java.lang.String>}
     * 
     */
    @XmlElementDecl(name = "organisationName", namespace = "http://www.opengis.net/wcs", scope = ResponsiblePartyType.class)
    public JAXBElement<String> createResponsiblePartyTypeOrganisationName(String value) {
        return new JAXBElement<String>(_ResponsiblePartyTypeOrganisationName_QNAME, ((Class) String.class), ResponsiblePartyType.class, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.ContactType>}
     * 
     */
    @XmlElementDecl(name = "contactInfo", namespace = "http://www.opengis.net/wcs", scope = ResponsiblePartyType.class)
    public JAXBElement<ContactType> createResponsiblePartyTypeContactInfo(ContactType value) {
        return new JAXBElement<ContactType>(_ResponsiblePartyTypeContactInfo_QNAME, ((Class) ContactType.class), ResponsiblePartyType.class, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<java.lang.String>}
     * 
     */
    @XmlElementDecl(name = "individualName", namespace = "http://www.opengis.net/wcs", scope = ResponsiblePartyType.class)
    public JAXBElement<String> createResponsiblePartyTypeIndividualName(String value) {
        return new JAXBElement<String>(_ResponsiblePartyTypeIndividualName_QNAME, ((Class) String.class), ResponsiblePartyType.class, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.AxisDescriptionType>}
     * 
     */
    @XmlElementDecl(name = "AxisDescription", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "_GML", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<AxisDescriptionType> createAxisDescription(AxisDescriptionType value) {
        return new JAXBElement<AxisDescriptionType>(_AxisDescription_QNAME, ((Class) AxisDescriptionType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.CoverageOfferingType>}
     * 
     */
    @XmlElementDecl(name = "CoverageOffering", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "_GML", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<CoverageOfferingType> createCoverageOffering(CoverageOfferingType value) {
        return new JAXBElement<CoverageOfferingType>(_CoverageOffering_QNAME, ((Class) CoverageOfferingType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.MetadataLinkType>}
     * 
     */
    @XmlElementDecl(name = "metadataLink", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "metaDataProperty", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<MetadataLinkType> createMetadataLink(MetadataLinkType value) {
        return new JAXBElement<MetadataLinkType>(_MetadataLink_QNAME, ((Class) MetadataLinkType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<java.lang.String>}
     * 
     */
    @XmlElementDecl(name = "description", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "description", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, ((Class) String.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.TimeSequenceType>}
     * 
     */
    @XmlElementDecl(name = "TimeSequence", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<TimeSequenceType> createTimeSequence(TimeSequenceType value) {
        return new JAXBElement<TimeSequenceType>(_TimeSequence_QNAME, ((Class) TimeSequenceType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.TimePeriodType>}
     * 
     */
    @XmlElementDecl(name = "timePeriod", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<TimePeriodType> createTimePeriod(TimePeriodType value) {
        return new JAXBElement<TimePeriodType>(_TimePeriod_QNAME, ((Class) TimePeriodType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.TimeSequenceType>}
     * 
     */
    @XmlElementDecl(name = "temporalDomain", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<TimeSequenceType> createTemporalDomain(TimeSequenceType value) {
        return new JAXBElement<TimeSequenceType>(_TemporalDomain_QNAME, ((Class) TimeSequenceType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.DomainSetType>}
     * 
     */
    @XmlElementDecl(name = "domainSet", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<DomainSetType> createDomainSet(DomainSetType value) {
        return new JAXBElement<DomainSetType>(_DomainSet_QNAME, ((Class) DomainSetType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.TypedLiteralType>}
     * 
     */
    @XmlElementDecl(name = "singleValue", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<TypedLiteralType> createSingleValue(TypedLiteralType value) {
        return new JAXBElement<TypedLiteralType>(_SingleValue_QNAME, ((Class) TypedLiteralType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.WCSCapabilitiesType>}
     * 
     */
    @XmlElementDecl(name = "WCS_Capabilities", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<WCSCapabilitiesType> createWCSCapabilities(WCSCapabilitiesType value) {
        return new JAXBElement<WCSCapabilitiesType>(_WCSCapabilities_QNAME, ((Class) WCSCapabilitiesType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.LonLatEnvelopeType>}
     * 
     */
    @XmlElementDecl(name = "lonLatEnvelope", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<LonLatEnvelopeType> createLonLatEnvelope(LonLatEnvelopeType value) {
        return new JAXBElement<LonLatEnvelopeType>(_LonLatEnvelope_QNAME, ((Class) LonLatEnvelopeType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.CoverageOfferingBriefType>}
     * 
     */
    @XmlElementDecl(name = "CoverageOfferingBrief", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "_GML", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<CoverageOfferingBriefType> createCoverageOfferingBrief(CoverageOfferingBriefType value) {
        return new JAXBElement<CoverageOfferingBriefType>(_CoverageOfferingBrief_QNAME, ((Class) CoverageOfferingBriefType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.InterpolationMethodType>}
     * 
     */
    @XmlElementDecl(name = "interpolationMethod", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<InterpolationMethodType> createInterpolationMethod(InterpolationMethodType value) {
        return new JAXBElement<InterpolationMethodType>(_InterpolationMethod_QNAME, ((Class) InterpolationMethodType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.SupportedCRSsType>}
     * 
     */
    @XmlElementDecl(name = "supportedCRSs", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<SupportedCRSsType> createSupportedCRSs(SupportedCRSsType value) {
        return new JAXBElement<SupportedCRSsType>(_SupportedCRSs_QNAME, ((Class) SupportedCRSsType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.SpatialDomainType>}
     * 
     */
    @XmlElementDecl(name = "spatialDomain", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<SpatialDomainType> createSpatialDomain(SpatialDomainType value) {
        return new JAXBElement<SpatialDomainType>(_SpatialDomain_QNAME, ((Class) SpatialDomainType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<java.lang.String>}
     * 
     */
    @XmlElementDecl(name = "name", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "name", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, ((Class) String.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.SupportedInterpolationsType>}
     * 
     */
    @XmlElementDecl(name = "supportedInterpolations", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<SupportedInterpolationsType> createSupportedInterpolations(SupportedInterpolationsType value) {
        return new JAXBElement<SupportedInterpolationsType>(_SupportedInterpolations_QNAME, ((Class) SupportedInterpolationsType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.adapter.wcs.model.version100.gml.CodeListType>}
     * 
     */
    @XmlElementDecl(name = "formats", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<CodeListType> createFormats(CodeListType value) {
        return new JAXBElement<CodeListType>(_Formats_QNAME, ((Class) CodeListType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.Interval>}
     * 
     */
    @XmlElementDecl(name = "interval", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<Interval> createInterval(Interval value) {
        return new JAXBElement<Interval>(_Interval_QNAME, ((Class) Interval.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.RangeSetType>}
     * 
     */
    @XmlElementDecl(name = "RangeSet", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "_GML", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<RangeSetType> createRangeSet(RangeSetType value) {
        return new JAXBElement<RangeSetType>(_RangeSet_QNAME, ((Class) RangeSetType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.ServiceType>}
     * 
     */
    @XmlElementDecl(name = "Service", namespace = "http://www.opengis.net/wcs", substitutionHeadName = "_GML", substitutionHeadNamespace = "http://www.opengis.net/gml")
    public JAXBElement<ServiceType> createService(ServiceType value) {
        return new JAXBElement<ServiceType>(_Service_QNAME, ((Class) ServiceType.class), null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement<org.n52.oxf.wcsModel.version100.wcsCapabilities.SupportedFormatsType>}
     * 
     */
    @XmlElementDecl(name = "supportedFormats", namespace = "http://www.opengis.net/wcs")
    public JAXBElement<SupportedFormatsType> createSupportedFormats(SupportedFormatsType value) {
        return new JAXBElement<SupportedFormatsType>(_SupportedFormats_QNAME, ((Class) SupportedFormatsType.class), null, value);
    }

}
