/**
 * ﻿Copyright (C) 2012
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.wcs.capabilities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.n52.oxf.wcs.model.CodeListType;


@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "ServiceType", namespace = "http://www.opengis.net/wcs")
public class ServiceType
    extends AbstractDescriptionType
{

    @XmlElement(name = "keywords", namespace = "http://www.opengis.net/wcs", type = Keywords.class)
    protected List<Keywords> keywords;
    @XmlElement(name = "responsibleParty", namespace = "http://www.opengis.net/wcs", type = ResponsiblePartyType.class)
    protected ResponsiblePartyType responsibleParty;
    @XmlElement(name = "fees", namespace = "http://www.opengis.net/wcs", type = CodeListType.class)
    protected CodeListType fees;
    @XmlElement(name = "accessConstraints", namespace = "http://www.opengis.net/wcs", type = CodeListType.class)
    protected List<CodeListType> accessConstraints;
    @XmlAttribute(name = "updateSequence", namespace = "")
    protected String updateSequence;
    @XmlAttribute(name = "version", namespace = "")
    protected String version;

    protected List<Keywords> _getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<Keywords>();
        }
        return keywords;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.n52.oxf.wcs.capabilities.Keywords}
     * 
     */
    public List<Keywords> getKeywords() {
        return this._getKeywords();
    }

    /**
     * Gets the value of the responsibleParty property.
     * 
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcs.capabilities.ResponsiblePartyType}
     */
    public ResponsiblePartyType getResponsibleParty() {
        return responsibleParty;
    }

    /**
     * Sets the value of the responsibleParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcs.capabilities.ResponsiblePartyType}
     */
    public void setResponsibleParty(ResponsiblePartyType value) {
        this.responsibleParty = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcs.model.CodeListType}
     */
    public CodeListType getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcs.model.CodeListType}
     */
    public void setFees(CodeListType value) {
        this.fees = value;
    }

    protected List<CodeListType> _getAccessConstraints() {
        if (accessConstraints == null) {
            accessConstraints = new ArrayList<CodeListType>();
        }
        return accessConstraints;
    }

    /**
     * Gets the value of the accessConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.n52.oxf.wcs.model.CodeListType}
     * 
     */
    public List<CodeListType> getAccessConstraints() {
        return this._getAccessConstraints();
    }

    /**
     * Gets the value of the updateSequence property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getUpdateSequence() {
        return updateSequence;
    }

    /**
     * Sets the value of the updateSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setUpdateSequence(String value) {
        this.updateSequence = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getVersion() {
        if (version == null) {
            return "1.0.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
