/**
 * ﻿Copyright (C) 2012-2014 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as publishedby the Free
 * Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of the
 * following licenses, the combination of the program with the linked library is
 * not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed under
 * the aforementioned licenses, is permitted by the copyright holders if the
 * distribution is compliant with both the GNU General Public License version 2
 * and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.wcs.capabilities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

import org.n52.oxf.wcs.model.PolygonType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "SpatialDomainType", namespace = "http://www.opengis.net/wcs")
public class SpatialDomainType {

    @XmlElementRef(name = "Envelope", namespace = "http://www.opengis.net/gml", type = JAXBElement.class)
    protected List<JAXBElement> envelope;
    @XmlElementRef(name = "Grid", namespace = "http://www.opengis.net/gml", type = JAXBElement.class)
    protected List<JAXBElement> grid;
    @XmlElement(name = "Polygon", namespace = "http://www.opengis.net/gml", type = PolygonType.class)
    protected List<PolygonType> polygon;

    protected List<JAXBElement> _getEnvelope() {
        if (envelope == null) {
            envelope = new ArrayList<JAXBElement>();
        }
        return envelope;
    }

    /**
     * Gets the value of the envelope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the envelope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnvelope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement<org.n52.oxf.adapter.wcs.model.version100.gml.EnvelopeWithTimePeriodType>}
     * {@link javax.xml.bind.JAXBElement<org.n52.oxf.adapter.wcs.model.version100.gml.EnvelopeType>}
     * 
     */
    public List<JAXBElement> getEnvelope() {
        return this._getEnvelope();
    }

    protected List<JAXBElement> _getGrid() {
        if (grid == null) {
            grid = new ArrayList<JAXBElement>();
        }
        return grid;
    }

    /**
     * Gets the value of the grid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement<org.n52.oxf.adapter.wcs.model.version100.gml.GridType>}
     * {@link javax.xml.bind.JAXBElement<org.n52.oxf.adapter.wcs.model.version100.gml.RectifiedGridType>}
     * 
     */
    public List<JAXBElement> getGrid() {
        return this._getGrid();
    }

    protected List<PolygonType> _getPolygon() {
        if (polygon == null) {
            polygon = new ArrayList<PolygonType>();
        }
        return polygon;
    }

    /**
     * Gets the value of the polygon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polygon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolygon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.n52.oxf.wcs.model.PolygonType}
     * 
     */
    public List<PolygonType> getPolygon() {
        return this._getPolygon();
    }

}
