/*
 * ﻿Copyright (C) 2012-2017 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the Free
 * Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of the
 * following licenses, the combination of the program with the linked library is
 * not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed under
 * the aforementioned licenses, is permitted by the copyright holders if the
 * distribution is compliant with both the GNU General Public License version 2
 * and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2005.06.25 at 02:38:11 CEST
//


package org.n52.oxf.wcs.capabilities;

//import com.sun.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "WCSCapabilityType", namespace = "http://www.opengis.net/wcs")
public class WCSCapabilityType {

    @XmlElement(name = "Request", namespace = "http://www.opengis.net/wcs", type = org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.class)
    protected org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request request;
    @XmlElement(name = "Exception", namespace = "http://www.opengis.net/wcs", type = org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception.class)
    protected org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception exception;
    @XmlElement(name = "VendorSpecificCapabilities", namespace = "http://www.opengis.net/wcs", type = org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities.class)
    protected org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities vendorSpecificCapabilities;
    @XmlAttribute(name = "updateSequence", namespace = "")
    protected String updateSequence;
    @XmlAttribute(name = "version", namespace = "")
    protected String version;

    /**
     * Gets the value of the request property.
     *
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request}
     */
    public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     *
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request}
     */
    public void setRequest(org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the exception property.
     *
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception}
     */
    public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception getException() {
        return exception;
    }

    /**
     * Sets the value of the exception property.
     *
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception}
     */
    public void setException(org.n52.oxf.wcs.capabilities.WCSCapabilityType.Exception value) {
        this.exception = value;
    }

    /**
     * Gets the value of the vendorSpecificCapabilities property.
     *
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities}
     */
    public org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities getVendorSpecificCapabilities() {
        return vendorSpecificCapabilities;
    }

    /**
     * Sets the value of the vendorSpecificCapabilities property.
     *
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities}
     */
    public void setVendorSpecificCapabilities(org.n52.oxf.wcs.capabilities.WCSCapabilityType.VendorSpecificCapabilities value) {
        this.vendorSpecificCapabilities = value;
    }

    /**
     * Gets the value of the updateSequence property.
     *
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getUpdateSequence() {
        return updateSequence;
    }

    /**
     * Sets the value of the updateSequence property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setUpdateSequence(String value) {
        this.updateSequence = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getVersion() {
        if (version == null) {
            return "1.0.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setVersion(String value) {
        this.version = value;
    }

    @XmlAccessorType(value = XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Exception {

        @XmlElement(name = "Format", namespace = "http://www.opengis.net/wcs", type = String.class)
        protected List<String> format;

        protected List<String> _getFormat() {
            if (format == null) {
                format = new ArrayList<>();
            }
            return format;
        }

        /**
         * Gets the value of the format property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the format property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFormat().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link java.lang.String}
         *
         * @return
         */
        public List<String> getFormat() {
            return this._getFormat();
        }

    }

    @XmlAccessorType(value = XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Request {

        @XmlElement(name = "GetCapabilities", namespace = "http://www.opengis.net/wcs", type = org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities.class)
        protected org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities getCapabilities;
        @XmlElement(name = "DescribeCoverage", namespace = "http://www.opengis.net/wcs", type = org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage.class)
        protected org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage describeCoverage;
        @XmlElement(name = "GetCoverage", namespace = "http://www.opengis.net/wcs", type = org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage.class)
        protected org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage getCoverage;

        /**
         * Gets the value of the getCapabilities property.
         *
         * @return
         *     possible object is
         *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities}
         */
        public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities getGetCapabilities() {
            return getCapabilities;
        }

        /**
         * Sets the value of the getCapabilities property.
         *
         * @param value
         *     allowed object is
         *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities}
         */
        public void setGetCapabilities(org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCapabilities value) {
            this.getCapabilities = value;
        }

        /**
         * Gets the value of the describeCoverage property.
         *
         * @return
         *     possible object is
         *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage}
         */
        public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage getDescribeCoverage() {
            return describeCoverage;
        }

        /**
         * Sets the value of the describeCoverage property.
         *
         * @param value
         *     allowed object is
         *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage}
         */
        public void setDescribeCoverage(org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.DescribeCoverage value) {
            this.describeCoverage = value;
        }

        /**
         * Gets the value of the getCoverage property.
         *
         * @return
         *     possible object is
         *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage}
         */
        public org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage getGetCoverage() {
            return getCoverage;
        }

        /**
         * Sets the value of the getCoverage property.
         *
         * @param value
         *     allowed object is
         *     {@link org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage}
         */
        public void setGetCoverage(org.n52.oxf.wcs.capabilities.WCSCapabilityType.Request.GetCoverage value) {
            this.getCoverage = value;
        }

        @XmlAccessorType(value = XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DescribeCoverage {

            @XmlElement(name = "DCPType", namespace = "http://www.opengis.net/wcs", type = DCPTypeType.class)
            protected List<DCPTypeType> dcpType;

            protected List<DCPTypeType> _getDCPType() {
                if (dcpType == null) {
                    dcpType = new ArrayList<>();
                }
                return dcpType;
            }

            /**
             * Gets the value of the dcpType property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dcpType property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDCPType().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.n52.oxf.wcs.capabilities.DCPTypeType}
             *
             * @return
             */
            public List<DCPTypeType> getDCPType() {
                return this._getDCPType();
            }

        }

        @XmlAccessorType(value = XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GetCapabilities {

            @XmlElement(name = "DCPType", namespace = "http://www.opengis.net/wcs", type = DCPTypeType.class)
            protected List<DCPTypeType> dcpType;

            protected List<DCPTypeType> _getDCPType() {
                if (dcpType == null) {
                    dcpType = new ArrayList<>();
                }
                return dcpType;
            }

            /**
             * Gets the value of the dcpType property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dcpType property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDCPType().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.n52.oxf.wcs.capabilities.DCPTypeType}
             *
             * @return
             */
            public List<DCPTypeType> getDCPType() {
                return this._getDCPType();
            }

        }

        @XmlAccessorType(value = XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GetCoverage {

            @XmlElement(name = "DCPType", namespace = "http://www.opengis.net/wcs", type = DCPTypeType.class)
            protected List<DCPTypeType> dcpType;

            protected List<DCPTypeType> _getDCPType() {
                if (dcpType == null) {
                    dcpType = new ArrayList<>();
                }
                return dcpType;
            }

            /**
             * Gets the value of the dcpType property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dcpType property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDCPType().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.n52.oxf.wcs.capabilities.DCPTypeType}
             *
             * @return
             */
            public List<DCPTypeType> getDCPType() {
                return this._getDCPType();
            }

        }

    }

    @XmlAccessorType(value = XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VendorSpecificCapabilities {

        //@XmlAnyElement(lax = true, value = W3CDomHandler.class)
        protected Object any;

        /**
         * Gets the value of the any property.
         *
         * @return
         *     possible object is
         *     {@link java.lang.Object}
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         *
         * @param value
         *     allowed object is
         *     {@link java.lang.Object}
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }

}
