/**
 * ﻿Copyright (C) 2012-2015 52°North Initiative for Geospatial Open Source
 * Software GmbH
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the Free
 * Software Foundation.
 *
 * If the program is linked with libraries which are licensed under one of the
 * following licenses, the combination of the program with the linked library is
 * not considered a "derivative work" of the program:
 *
 *     - Apache License, version 2.0
 *     - Apache Software License, version 1.0
 *     - GNU Lesser General Public License, version 3
 *     - Mozilla Public License, versions 1.0, 1.1 and 2.0
 *     - Common Development and Distribution License (CDDL), version 1.0
 *
 * Therefore the distribution of the program linked with libraries licensed under
 * the aforementioned licenses, is permitted by the copyright holders if the
 * distribution is compliant with both the GNU General Public License version 2
 * and the aforementioned licenses.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.wcs.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "TimePositionType", namespace = "http://www.opengis.net/gml")
public class TimePositionType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "calendarEraName", namespace = "")
    protected String calendarEraName;
    @XmlAttribute(name = "frame", namespace = "")
    protected String frame;
    @XmlAttribute(name = "indeterminatePosition", namespace = "")
    protected TimeIndeterminateValueType indeterminatePosition;

    /**
     * Here we have collapsed the hierarchy of subtypes for temporal position in 19108
     * by defining a union of simple types for indicating temporal position relative to a
     * specific reference system.
     * Date and time may be indicated with varying degrees of precision:
     * year, year-month, date, or dateTime (all ISO 8601 format). Note
     * that the dateTime type does not allow right-truncation (i.e. omitting
     * seconds). An ordinal era may be referenced via URI, and a decimal value
     * can be used to indicate the distance from the scale origin (e.g. UNIX time,
     * GPS calendar).
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getValue() {
        return value;
    }

    /**
     * Here we have collapsed the hierarchy of subtypes for temporal position in 19108
     * by defining a union of simple types for indicating temporal position relative to a
     * specific reference system.
     * Date and time may be indicated with varying degrees of precision:
     * year, year-month, date, or dateTime (all ISO 8601 format). Note
     * that the dateTime type does not allow right-truncation (i.e. omitting
     * seconds). An ordinal era may be referenced via URI, and a decimal value
     * can be used to indicate the distance from the scale origin (e.g. UNIX time,
     * GPS calendar).
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the calendarEraName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getCalendarEraName() {
        return calendarEraName;
    }

    /**
     * Sets the value of the calendarEraName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setCalendarEraName(String value) {
        this.calendarEraName = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getFrame() {
        if (frame == null) {
            return "#ISO-8601";
        } else {
            return frame;
        }
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setFrame(String value) {
        this.frame = value;
    }

    /**
     * Gets the value of the indeterminatePosition property.
     * 
     * @return
     *     possible object is
     *     {@link org.n52.oxf.wcs.model.TimeIndeterminateValueType}
     */
    public TimeIndeterminateValueType getIndeterminatePosition() {
        return indeterminatePosition;
    }

    /**
     * Sets the value of the indeterminatePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.n52.oxf.wcs.model.TimeIndeterminateValueType}
     */
    public void setIndeterminatePosition(TimeIndeterminateValueType value) {
        this.indeterminatePosition = value;
    }

}
