//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.serviceAdapters.wcs.model.version100.gml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "AbstractGeometryType", namespace = "http://www.opengis.net/gml")
public abstract class AbstractGeometryType
    extends AbstractGeometryBaseType
{

    @XmlAttribute(name = "srsName", namespace = "")
    protected String srsName;

    /**
     * Gets the value of the srsName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getSrsName() {
        return srsName;
    }

    /**
     * Sets the value of the srsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setSrsName(String value) {
        this.srsName = value;
    }

}
