//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.serviceAdapters.wcs.model.version100.gml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "BoundingShapeType", namespace = "http://www.opengis.net/gml")
public class BoundingShapeType {

    @XmlElementRef(name = "Envelope", namespace = "http://www.opengis.net/gml", type = JAXBElement.class)
    protected JAXBElement envelope;

    /**
     * Gets the value of the envelope property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement<org.n52.oxf.serviceAdapters.wcs.model.version100.gml.EnvelopeWithTimePeriodType>}
     *     {@link javax.xml.bind.JAXBElement<org.n52.oxf.serviceAdapters.wcs.model.version100.gml.EnvelopeType>}
     */
    public JAXBElement getEnvelope() {
        return envelope;
    }

    /**
     * Sets the value of the envelope property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement<org.n52.oxf.serviceAdapters.wcs.model.version100.gml.EnvelopeWithTimePeriodType>}
     *     {@link javax.xml.bind.JAXBElement<org.n52.oxf.serviceAdapters.wcs.model.version100.gml.EnvelopeType>}
     */
    public void setEnvelope(JAXBElement value) {
        this.envelope = value;
    }

}
