//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.serviceAdapters.wcs.model.version100.gml;

//import com.sun.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlType(name = "GridEnvelopeType", namespace = "http://www.opengis.net/gml")
public class GridEnvelopeType {

    //@XmlList
    @XmlElement(name = "low", namespace = "http://www.opengis.net/gml", type = BigInteger.class)
    protected List<BigInteger> low;
    
    //@XmlList
    @XmlElement(name = "high", namespace = "http://www.opengis.net/gml", type = BigInteger.class)
    protected List<BigInteger> high;

    protected List<BigInteger> _getLow() {
        if (low == null) {
            low = new ArrayList<BigInteger>();
        }
        return low;
    }

    /**
     * Gets the value of the low property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the low property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.math.BigInteger}
     * 
     */
    public List<BigInteger> getLow() {
        return this._getLow();
    }

    protected List<BigInteger> _getHigh() {
        if (high == null) {
            high = new ArrayList<BigInteger>();
        }
        return high;
    }

    /**
     * Gets the value of the high property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the high property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHigh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.math.BigInteger}
     * 
     */
    public List<BigInteger> getHigh() {
        return this._getHigh();
    }

}
