//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b11-EA 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.25 at 02:38:11 CEST 
//


package org.n52.oxf.serviceAdapters.wcs.model.version100.gml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * Java content class for TimeIndeterminateValueType.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;simpleType name="TimeIndeterminateValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="after"/>
 *     &lt;enumeration value="before"/>
 *     &lt;enumeration value="now"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum(value = String.class)
public enum TimeIndeterminateValueType {

    @XmlEnumValue(value = "unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue(value = "before")
    BEFORE("before"),
    @XmlEnumValue(value = "now")
    NOW("now"),
    @XmlEnumValue(value = "after")
    AFTER("after");
    public final String value;

    TimeIndeterminateValueType(String v) {
        value = v;
    }

}
