package org.n52.swes;

import org.n52.ows.exception.OwsException;

/**
 * Request does not conform to its XML Schema definition.
 */
public class InvalidRequestException extends OwsException {

    private static final long serialVersionUID = 4691809997561218234L;

    /**
     * @param locator Exception message generated by validator
     */
    public InvalidRequestException(String locator) {
        super(SwesExceptionCode.INVALID_REQUEST.getExceptionCode(), locator);
    }

    @Override
    public int getHttpStatusCode() {
        // not found in specification, so we assume a BAD_REQUEST here
        return BAD_REQUEST;
    }

}
